### ISSUE TITLE
Outdated Mongo Dockerfile

### ISSUE THREAD

**Issue by IsraelFM** [nitin27may/mean-docker#11]
The Dockerfile in the mongo folder is copying a non-existent "init-mongo.sh" file.
`COPY init-mongo.sh /docker-entrypoint-initdb.d`

From what I saw in the update 15 days ago, it was necessary to update here and README.md too.
`COPY init-db.d /docker-entrypoint-initdb.d`

I want to take the opportunity to congratulate you for the excellent work with this stack.

**Comment by nitin27may** [comment]
Hi @IsraelFM , Thank you.

Initially plan was to use mongdb custom dockerfile but as you can see that I am using mongodb as image in docker-compose file, I am not referring dockerfile from mongo folder. I will update repo.
Either I will add one example to use that custom dockerfile  repo or will remove that file to avoid any further confusion.

**Comment by nitin27may** [comment]
[](url)

**Comment by nitin27may** [comment]
[Fixed with Commit](https://github.com/nitin27may/mean-docker/commit/482571be1c04822be5f2106b267f65e2572e0cbd)

**Comment by nitin27may** [comment]
[Fixed with Commit](https://github.com/nitin27may/mean-docker/commit/482571be1c04822be5f2106b267f65e2572e0cbd)
