### ISSUE TITLE
ERROR: Service 'angular' failed to build: failed to register layer: Error processing tar file(exit status 1): write /usr/share/mime/audio/x-adpcm.xml: no space left on device

### ISSUE THREAD

**Issue by dillashawbones** [nitin27may/mean-docker#13]
When running the docker-compose command, an error "no space left on device" is displayed despite, df command showing only 13% of disk is utilized
![Screenshot from 2020-09-08 23-16-00](https://user-images.githubusercontent.com/70971787/92510514-9aa05080-f229-11ea-89d2-f2f1b935d756.png)

**Comment by nitin27may** [comment]
It's not docker-compose file issue. 
Run `sudo docker image prune -f` && `sudo docker container prune -f ` This cleans up the dangling images and dead containers.

**Comment by dillashawbones** [comment]
I ran both the commands,however, the issue still persists.

**Comment by nitin27may** [comment]
It's more about how you have installed / configured docker. Below are few links to fix same.

https://unix.stackexchange.com/questions/571899/docker-failed-to-register-layer-error-processing-tar-fileexit-status-1-no-s

https://unix.stackexchange.com/questions/96299/no-space-left-on-device-debian
