### ISSUE TITLE
docker compose up debug problem

### ISSUE THREAD

**Issue by matteoventuri7** [nitin27may/mean-docker#45]
Hi, i'm trying to launch the project but after the command docker-compose -f "docker-compose.debug.yml" up the mean-angular container doesn't start and into the logs i read this: An unhandled exception occurred: ENOENT: no such file or directory, lstat '/app/src/styles.scss'

**Comment by nitin27may** [comment]
Could you please add more details ? I tried and it is working perfectly. Could you please take latest and try.

**Comment by nitin27may** [comment]
Closing it, as it is working as expected. If still facing an issue open an issue with Environment details.
