### ISSUE TITLE
docker compose up debug problem (mongo)

### ISSUE THREAD

**Issue by matteoventuri7** [nitin27may/mean-docker#46]
Hi, after the command docker-compose -f "docker-compose.debug.yml" up I receive this error message: invalid mount config for type "bind": bind source path does not exist: /com.docker.devenvironments.code/mongo/init-db.d
I can continu only if i comment the bind line.

**Comment by nitin27may** [comment]
Could you please add more details (environment, docker version)? I tried and it is working perfectly. Could you please take latest and try.

**Comment by nitin27may** [comment]
Closing it, as it is working as expected. If still facing an issue open an issue with Environment details.
