### ISSUE TITLE
Docker compose nginx problem

### ISSUE THREAD

**Issue by matteoventuri7** [nitin27may/mean-docker#47]
Hi, launching command docker-compose against nginx docker compose file i receive this error:
#19 18.88 npm ERR! Could not resolve dependency:
#19 18.88 npm ERR! peer @angular/animations@"^13.0.0" from ngx-bootstrap@8.0.0
#19 18.88 npm ERR! node_modules/ngx-bootstrap
#19 18.88 npm ERR!   ngx-bootstrap@"^8.0.0" from the root project
#19 18.88 npm ERR! 
#19 18.88 npm ERR! Conflicting peer dependency: @angular/animations@13.3.11
#19 18.88 npm ERR! node_modules/@angular/animations
#19 18.88 npm ERR!   peer @angular/animations@"^13.0.0" from ngx-bootstrap@8.0.0
#19 18.88 npm ERR!   node_modules/ngx-bootstrap
#19 18.88 npm ERR!     ngx-bootstrap@"^8.0.0" from the root project
#19 18.88 npm ERR! 
#19 18.88 npm ERR! Fix the upstream dependency conflict, or retry
#19 18.88 npm ERR! this command with --force, or --legacy-peer-deps
#19 18.88 npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by nitin27may** [comment]
Could you please add more details ? I tried and it is working perfectly. Could you please take latest and try.

**Comment by nitin27may** [comment]
Closing it, as it is working as expected. If still facing an issue open an issue with Environment details.
