### ISSUE TITLE
Error in `init-mongo.sh` while testing with docker

### ISSUE THREAD

**Issue by shankari** [nitin27may/mean-docker#6]
I just checked out this repo to experiment with it, but I can't get it to start up correctly.
I have not made any changes to any files

```
$ git diff
$
```

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

Yet, when I run `$ docker-compose`, I get the following error

```
mean_mongo  | 2020-07-21T05:05:07.455+0000 I  INDEX    [conn2] index build: done building index user_1_db_1 on ns admin.system.users
mean_mongo  | Successfully added user: {
mean_mongo  | 	"user" : "admin-user",
mean_mongo  | 	"roles" : [
mean_mongo  | 		{
mean_mongo  | 			"role" : "root",
mean_mongo  | 			"db" : "admin"
mean_mongo  | 		}
mean_mongo  | 	]
mean_mongo  | }
mean_mongo  | 2020-07-21T05:05:07.457+0000 E  -        [main] Error saving history file: FileOpenFailed: Unable to open() file /home/mongodb/.dbshell: No such file or directory
mean_mongo  | 2020-07-21T05:05:07.458+0000 I  NETWORK  [conn2] end connection 127.0.0.1:57972 (0 connections now open)
mean_mongo  |
mean_mongo  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-mongo.sh
mean_mongo  | /docker-entrypoint-initdb.d/init-mongo.sh: line 1: $8: unbound variable
mean_mongo exited with code 1
```

I am not quite sure where the `$8` comes from. Is it maybe from the hardcoded sample password? But that is not line 1. But since you are using << EOF, maybe the entire script looks like the first line?

Have you seen this error before?

**Comment by nitin27may** [comment]
I got this reference https://github.com/docker-library/mongo/issues/323

I have added .dbshell file in mongo folder and mapped it in volume to solve this issue.

**Comment by shankari** [comment]
Cool. I ended up using the server code from [the MERN stack example](https://github.com/t-ho/mern-stack) so this is no longer a blocker for me. But hopefully the next person to try this out will find it easier.

Thanks for the contribution - this is the only current angular e2e demo that I could find.

**Comment by nitin27may** [comment]
You are welcome.
