### ISSUE TITLE
Front is not running (Dev mode)

### ISSUE THREAD

**Issue by bmlaghui** [nitin27may/mean-docker#79]
When i run the project with the docker-compose.debug.yml, the front is not working

**Comment by nitin27may** [comment]
Resolved, merged in master

**Comment by bmlaghui** [comment]
Sorry, still not working for me

**Comment by nitin27may** [comment]
Could you please add more details for it ? What error you are getting ? What Os you are using ?

**Comment by bmlaghui** [comment]
I' using windows as OS, so i deleted the sudo before chmod ... and i used the terminal as administrator,
i have this error message :

=> [express internal] load build context                                                                           0.0s
 => => transferring context: 2.00kB                                                                                 0.0s
 => [express  1/18] FROM docker.io/library/node:20@sha256:5f21943fe97b24ae1740da6d7b9c56ac43fe3495acb47c1b232b0a35  0.0s 
 => CACHED [express  2/18] WORKDIR /api                                                                             0.0s 
 => CACHED [express  3/18] RUN  chown -R node:node /api                                                             0.0s 
 => CACHED [express  4/18] COPY --chown=node:node package*.json .                                                   0.0s 
 => ERROR [express  5/18] RUN npm ci                                                                                1.5s 
------
 > [express  5/18] RUN npm ci:
1.414 npm ERR! code EUSAGE
1.422 npm ERR!
1.422 npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
1.422 npm ERR!
1.423 npm ERR! Missing: app-root-path@3.1.0 from lock file
1.423 npm ERR!
1.423 npm ERR! Clean install a project
1.424 npm ERR!
1.424 npm ERR! Usage:
1.424 npm ERR! npm ci
1.424 npm ERR!
1.424 npm ERR! Options:
1.424 npm ERR! [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
1.424 npm ERR! [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
1.424 npm ERR! [--strict-peer-deps] [--foreground-scripts] [--ignore-scripts] [--no-audit]
1.424 npm ERR! [--no-bin-links] [--no-fund] [--dry-run]
1.424 npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
1.424 npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
1.424 npm ERR!
1.425 npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
1.425 npm ERR!
1.425 npm ERR! Run "npm help ci" for more info
1.435
1.435 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-11-17T07_17_04_792Z-debug-0.log
------
failed to solve: process "/bin/sh -c npm ci" did not complete successfully: exit code: 1

**Comment by nitin27may** [comment]
Please check now.

**Comment by bmlaghui** [comment]
Hello,
now the front is running but the back is crashed. 
Also the host of back called is locahost:4200/api (normaly it should be localhost:3000/api)

------------------------------
this is the error when i try to connect in the front
Error occurred while trying to proxy: localhost:4200/api/user/authenticate
--------------------
this is the error displayed on ther terminal
mean_express  | [nodemon] app crashed - waiting for file changes before starting...
mean_angular  | 
mean_angular  | Warning: This is a simple server for use in testing or debugging Angular applications
mean_angular  | locally. It hasn't been reviewed for security issues.
mean_angular  | 
mean_angular  | Binding this server to an open connection can result in compromising your application or
mean_angular  | computer. Using a different host than the one passed to the "--host" flag might result in
mean_angular  | websocket connection issues. You might need to use "--disable-host-check" if that's the
mean_angular  | case.
mean_angular  | 
mean_angular  | One or more browsers which are configured in the project's Browserslist configuration will be ignored as ES5 output 
is not supported by the Angular CLI.
mean_angular  | Ignored browsers: kaios 2.5, op_mini all
mean_angular  | - Generating browser application bundles (phase: setup)...

**Comment by nitin27may** [comment]
It is using proxy for all api calls, please check package.json, 'ng serve --proxy-config proxy.conf.json' , it use proxy.conf.json file for configuration.

Could you please build with no cache 

'Docker compose build --no-cache'

**Comment by bmlaghui** [comment]
In the package.json (front) i have :
"scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.conf.json --host 0.0.0.0 --watch --poll 2000",
    "serve": "ng serve --proxy-config proxy.conf.json",
    "build": "ng build --configuration production",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "dev:ssr": "ng run frontend:serve-ssr",
    "serve:ssr": "node dist/frontend/server/main.js",
    "build:prod": "ng build --configuration production --output-path=dist",
    "build:ssr": "ng build --configuration production && ng run frontend:server:production",
    "build:output": "npm run build:ssr --output-path=dist",
    "prerender": "ng run frontend:prerender",
    "dev-server": "concurrently \"nodemon ../api/server.js --watch api\" \"npm run serve\""
  },
  and in the docker-compose.debug.yml i added args:  - "--no-cache" to the express
   express: #name of the second service
    build: # specify the directory of the Dockerfile
      context: ./api
      dockerfile: debug.dockerfile
      args:
        - "--no-cache"
    container_name: mean_express
    volumes:
      - ./api:/api
    ports:
      - "3000:3000" #specify ports forewarding
    environment:
      - SECRET=Thisismysecret
      - NODE_ENV=development
      - MONGO_DB_USERNAME=admin-user
      - MONGO_DB_PASSWORD=admin-password
      - MONGO_DB_HOST=database
      - MONGO_DB_PORT=
      - MONGO_DB_PARAMETERS=?authSource=admin
      - MONGO_DB_DATABASE=mean-contacts
    links:
      - database




but i have the same problem

**Comment by nitin27may** [comment]
Hi @bmlaghui ,

I just recloned, and build the project `docker compose -f 'docker-compose.debug.yml' build --no-cache` 

After that I ran `docker compose -f 'docker-compose.debug.yml` up' and it is working as expected. 

Could you please make sure that You have all latest and then run above ?

**Comment by bmlaghui** [comment]
hi!,
it's working for me , i've replaced the express specification the the docker-compose.debug.yml same as docker-compose.nginx.yml
