### ISSUE TITLE
Compose Debug Issue

### ISSUE THREAD

**Issue by metcalfc** [nitin27may/mean-docker#8]
One change that might be good to make is to update the version to 3.8

```
version: "3.8" 
```

Version 3 is old and is different enough. We're moving to a versionless schema in the future.

**Comment by metcalfc** [comment]
When I update the version and run the debug compose file in the branch I get:

```
mean_express | connection string mongodb://admin-user:admin-password@database/mean-contacts?authSource=admin
mean_express | secret undefined
mean_express | /app/node_modules/express-jwt/lib/index.js:20
mean_express |   if (!options || !options.secret) throw new Error('secret should be set');
mean_express |                                    ^
```

**Comment by nitin27may** [comment]
Hi @metcalfc , I added missing variable (that was SECRET, used for JWT) and also updated compose file version. checked app, able to run it locally.

**Comment by nitin27may** [comment]
Hi @metcalfc , finally figured out configuration for nodejs (expresjs). I had to add const HOST = "0.0.0.0" in  server.js and pass it to in app.listen. Also, had to do mapping of code and node_modules in compose file. 
I will look in to Angular project now :)

**Comment by nitin27may** [comment]
:) @metcalfc I solved the configuration issue for Angular Project too. Now I am able to debug Expressjs and Angular both in containers. It's available in docker-dev branch, I will merge it after running few tests.
Thank you

**Comment by nitin27may** [comment]
using compose file 'docker-compose.nginx.yml', I am able to debug both Angular and expresjs just after running `docker-compose -f 'docker-compose.nginx.yml' up`
